# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cipr < Formula
  desc ""
  homepage "https://github.com/kaumnen/homebrew-tap"
  version "0.8.4"

  on_macos do
    url "https://github.com/kaumnen/cipr/releases/download/v0.8.4/cipr_0.8.4_darwin_all.tar.gz"
    sha256 "69badb0ed395629427b61e5b974cdc6f1da755c44e4993ddc5cd26653a009162"

    def install
      bin.install "cipr"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaumnen/cipr/releases/download/v0.8.4/cipr_0.8.4_linux_amd64.tar.gz"
        sha256 "2243a2a5c181bdd9fac51f450149ea1e15d380adc91d4454dd434a6da3323f3a"

        def install
          bin.install "cipr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaumnen/cipr/releases/download/v0.8.4/cipr_0.8.4_linux_arm64.tar.gz"
        sha256 "17144332cd918c72fdd6ca502b8059a3481a0407d6d8f1efc6a2483bc09e1171"

        def install
          bin.install "cipr"
        end
      end
    end
  end
end
