# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cipr < Formula
  desc ""
  homepage "https://github.com/kaumnen/homebrew-tap"
  version "0.8.12"

  on_macos do
    url "https://github.com/kaumnen/cipr/releases/download/v0.8.12/cipr_0.8.12_darwin_all.tar.gz"
    sha256 "7522dcb33cd9fd4435da3704542a271239f43c298123cf5992632f3fb9fc814c"

    def install
      bin.install "cipr"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaumnen/cipr/releases/download/v0.8.12/cipr_0.8.12_linux_amd64.tar.gz"
        sha256 "9abdf4b0ef79f8355d68808054ef37adcf32a07f4582e7b0f8e65ac2377230d1"

        def install
          bin.install "cipr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaumnen/cipr/releases/download/v0.8.12/cipr_0.8.12_linux_arm64.tar.gz"
        sha256 "d6a785011a15ad8d016315d95f59fb00ef2e7a8c8e608400783e62a81ee9358a"

        def install
          bin.install "cipr"
        end
      end
    end
  end
end
